// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: dict/dict.proto

package dict

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MaxRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []int32 `protobuf:"varint,1,rep,packed,name=data,proto3" json:"data,omitempty"`
}

func (x *MaxRequest) Reset() {
	*x = MaxRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dict_dict_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MaxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaxRequest) ProtoMessage() {}

func (x *MaxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dict_dict_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaxRequest.ProtoReflect.Descriptor instead.
func (*MaxRequest) Descriptor() ([]byte, []int) {
	return file_dict_dict_proto_rawDescGZIP(), []int{0}
}

func (x *MaxRequest) GetData() []int32 {
	if x != nil {
		return x.Data
	}
	return nil
}

type MaxResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Max int32 `protobuf:"varint,1,opt,name=max,proto3" json:"max,omitempty"`
}

func (x *MaxResponse) Reset() {
	*x = MaxResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dict_dict_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MaxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaxResponse) ProtoMessage() {}

func (x *MaxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dict_dict_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaxResponse.ProtoReflect.Descriptor instead.
func (*MaxResponse) Descriptor() ([]byte, []int) {
	return file_dict_dict_proto_rawDescGZIP(), []int{1}
}

func (x *MaxResponse) GetMax() int32 {
	if x != nil {
		return x.Max
	}
	return 0
}

type DictionaryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Word string `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
}

func (x *DictionaryRequest) Reset() {
	*x = DictionaryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dict_dict_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DictionaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DictionaryRequest) ProtoMessage() {}

func (x *DictionaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dict_dict_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DictionaryRequest.ProtoReflect.Descriptor instead.
func (*DictionaryRequest) Descriptor() ([]byte, []int) {
	return file_dict_dict_proto_rawDescGZIP(), []int{2}
}

func (x *DictionaryRequest) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

type DictionaryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Definition string `protobuf:"bytes,1,opt,name=definition,proto3" json:"definition,omitempty"`
}

func (x *DictionaryResponse) Reset() {
	*x = DictionaryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dict_dict_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DictionaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DictionaryResponse) ProtoMessage() {}

func (x *DictionaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dict_dict_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DictionaryResponse.ProtoReflect.Descriptor instead.
func (*DictionaryResponse) Descriptor() ([]byte, []int) {
	return file_dict_dict_proto_rawDescGZIP(), []int{3}
}

func (x *DictionaryResponse) GetDefinition() string {
	if x != nil {
		return x.Definition
	}
	return ""
}

type CreateDictionaryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Word       string `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
	Definition string `protobuf:"bytes,2,opt,name=definition,proto3" json:"definition,omitempty"`
}

func (x *CreateDictionaryRequest) Reset() {
	*x = CreateDictionaryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dict_dict_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateDictionaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDictionaryRequest) ProtoMessage() {}

func (x *CreateDictionaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dict_dict_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDictionaryRequest.ProtoReflect.Descriptor instead.
func (*CreateDictionaryRequest) Descriptor() ([]byte, []int) {
	return file_dict_dict_proto_rawDescGZIP(), []int{4}
}

func (x *CreateDictionaryRequest) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

func (x *CreateDictionaryRequest) GetDefinition() string {
	if x != nil {
		return x.Definition
	}
	return ""
}

type CreateDictionaryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateDictionaryResponse) Reset() {
	*x = CreateDictionaryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dict_dict_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateDictionaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDictionaryResponse) ProtoMessage() {}

func (x *CreateDictionaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dict_dict_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDictionaryResponse.ProtoReflect.Descriptor instead.
func (*CreateDictionaryResponse) Descriptor() ([]byte, []int) {
	return file_dict_dict_proto_rawDescGZIP(), []int{5}
}

type GetDictionaryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *GetDictionaryRequest) Reset() {
	*x = GetDictionaryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dict_dict_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDictionaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDictionaryRequest) ProtoMessage() {}

func (x *GetDictionaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dict_dict_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDictionaryRequest.ProtoReflect.Descriptor instead.
func (*GetDictionaryRequest) Descriptor() ([]byte, []int) {
	return file_dict_dict_proto_rawDescGZIP(), []int{6}
}

func (x *GetDictionaryRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetDictionaryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *GetDictionaryResponse) Reset() {
	*x = GetDictionaryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dict_dict_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDictionaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDictionaryResponse) ProtoMessage() {}

func (x *GetDictionaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dict_dict_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDictionaryResponse.ProtoReflect.Descriptor instead.
func (*GetDictionaryResponse) Descriptor() ([]byte, []int) {
	return file_dict_dict_proto_rawDescGZIP(), []int{7}
}

func (x *GetDictionaryResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type SumArrRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []int32 `protobuf:"varint,1,rep,packed,name=data,proto3" json:"data,omitempty"`
}

func (x *SumArrRequest) Reset() {
	*x = SumArrRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dict_dict_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SumArrRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SumArrRequest) ProtoMessage() {}

func (x *SumArrRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dict_dict_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SumArrRequest.ProtoReflect.Descriptor instead.
func (*SumArrRequest) Descriptor() ([]byte, []int) {
	return file_dict_dict_proto_rawDescGZIP(), []int{8}
}

func (x *SumArrRequest) GetData() []int32 {
	if x != nil {
		return x.Data
	}
	return nil
}

type SumArrResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sum int32 `protobuf:"varint,1,opt,name=sum,proto3" json:"sum,omitempty"`
}

func (x *SumArrResponse) Reset() {
	*x = SumArrResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dict_dict_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SumArrResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SumArrResponse) ProtoMessage() {}

func (x *SumArrResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dict_dict_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SumArrResponse.ProtoReflect.Descriptor instead.
func (*SumArrResponse) Descriptor() ([]byte, []int) {
	return file_dict_dict_proto_rawDescGZIP(), []int{9}
}

func (x *SumArrResponse) GetSum() int32 {
	if x != nil {
		return x.Sum
	}
	return 0
}

type CurrencyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ValuteName string `protobuf:"bytes,1,opt,name=valuteName,proto3" json:"valuteName,omitempty"`
}

func (x *CurrencyRequest) Reset() {
	*x = CurrencyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dict_dict_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CurrencyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrencyRequest) ProtoMessage() {}

func (x *CurrencyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dict_dict_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrencyRequest.ProtoReflect.Descriptor instead.
func (*CurrencyRequest) Descriptor() ([]byte, []int) {
	return file_dict_dict_proto_rawDescGZIP(), []int{10}
}

func (x *CurrencyRequest) GetValuteName() string {
	if x != nil {
		return x.ValuteName
	}
	return ""
}

type CurrencyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Code      string `protobuf:"bytes,2,opt,name=Code,proto3" json:"Code,omitempty"`
	Ccy       string `protobuf:"bytes,3,opt,name=Ccy,proto3" json:"Ccy,omitempty"`
	CcyNm_RU  string `protobuf:"bytes,4,opt,name=CcyNm_RU,json=CcyNmRU,proto3" json:"CcyNm_RU,omitempty"`
	CcyNm_UZ  string `protobuf:"bytes,5,opt,name=CcyNm_UZ,json=CcyNmUZ,proto3" json:"CcyNm_UZ,omitempty"`
	CcyNm_UZC string `protobuf:"bytes,6,opt,name=CcyNm_UZC,json=CcyNmUZC,proto3" json:"CcyNm_UZC,omitempty"`
	CcyNm_EN  string `protobuf:"bytes,7,opt,name=CcyNm_EN,json=CcyNmEN,proto3" json:"CcyNm_EN,omitempty"`
	Nominal   string `protobuf:"bytes,8,opt,name=Nominal,proto3" json:"Nominal,omitempty"`
	Rate      string `protobuf:"bytes,9,opt,name=Rate,proto3" json:"Rate,omitempty"`
	Diff      string `protobuf:"bytes,10,opt,name=Diff,proto3" json:"Diff,omitempty"`
	Date      string `protobuf:"bytes,11,opt,name=Date,proto3" json:"Date,omitempty"`
}

func (x *CurrencyResponse) Reset() {
	*x = CurrencyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dict_dict_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CurrencyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrencyResponse) ProtoMessage() {}

func (x *CurrencyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dict_dict_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrencyResponse.ProtoReflect.Descriptor instead.
func (*CurrencyResponse) Descriptor() ([]byte, []int) {
	return file_dict_dict_proto_rawDescGZIP(), []int{11}
}

func (x *CurrencyResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CurrencyResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CurrencyResponse) GetCcy() string {
	if x != nil {
		return x.Ccy
	}
	return ""
}

func (x *CurrencyResponse) GetCcyNm_RU() string {
	if x != nil {
		return x.CcyNm_RU
	}
	return ""
}

func (x *CurrencyResponse) GetCcyNm_UZ() string {
	if x != nil {
		return x.CcyNm_UZ
	}
	return ""
}

func (x *CurrencyResponse) GetCcyNm_UZC() string {
	if x != nil {
		return x.CcyNm_UZC
	}
	return ""
}

func (x *CurrencyResponse) GetCcyNm_EN() string {
	if x != nil {
		return x.CcyNm_EN
	}
	return ""
}

func (x *CurrencyResponse) GetNominal() string {
	if x != nil {
		return x.Nominal
	}
	return ""
}

func (x *CurrencyResponse) GetRate() string {
	if x != nil {
		return x.Rate
	}
	return ""
}

func (x *CurrencyResponse) GetDiff() string {
	if x != nil {
		return x.Diff
	}
	return ""
}

func (x *CurrencyResponse) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type PdfReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RawPath string `protobuf:"bytes,1,opt,name=rawPath,proto3" json:"rawPath,omitempty"`
}

func (x *PdfReq) Reset() {
	*x = PdfReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dict_dict_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PdfReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PdfReq) ProtoMessage() {}

func (x *PdfReq) ProtoReflect() protoreflect.Message {
	mi := &file_dict_dict_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PdfReq.ProtoReflect.Descriptor instead.
func (*PdfReq) Descriptor() ([]byte, []int) {
	return file_dict_dict_proto_rawDescGZIP(), []int{12}
}

func (x *PdfReq) GetRawPath() string {
	if x != nil {
		return x.RawPath
	}
	return ""
}

type PdfRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReadyPath string `protobuf:"bytes,1,opt,name=readyPath,proto3" json:"readyPath,omitempty"`
}

func (x *PdfRes) Reset() {
	*x = PdfRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dict_dict_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PdfRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PdfRes) ProtoMessage() {}

func (x *PdfRes) ProtoReflect() protoreflect.Message {
	mi := &file_dict_dict_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PdfRes.ProtoReflect.Descriptor instead.
func (*PdfRes) Descriptor() ([]byte, []int) {
	return file_dict_dict_proto_rawDescGZIP(), []int{13}
}

func (x *PdfRes) GetReadyPath() string {
	if x != nil {
		return x.ReadyPath
	}
	return ""
}

var File_dict_dict_proto protoreflect.FileDescriptor

var file_dict_dict_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x64, 0x69, 0x63, 0x74, 0x2f, 0x64, 0x69, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x04, 0x64, 0x69, 0x63, 0x74, 0x22, 0x20, 0x0a, 0x0a, 0x4d, 0x61, 0x78, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x05, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x1f, 0x0a, 0x0b, 0x4d, 0x61, 0x78,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x61, 0x78, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6d, 0x61, 0x78, 0x22, 0x27, 0x0a, 0x11, 0x44, 0x69,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x77,
	0x6f, 0x72, 0x64, 0x22, 0x34, 0x0a, 0x12, 0x44, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72,
	0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x65, 0x66,
	0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64,
	0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x4d, 0x0a, 0x17, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x44, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x65, 0x66, 0x69,
	0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x65,
	0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x1a, 0x0a, 0x18, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x44, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x28, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x44, 0x69, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x61, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x2d,
	0x0a, 0x15, 0x47, 0x65, 0x74, 0x44, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x23, 0x0a,
	0x0d, 0x53, 0x75, 0x6d, 0x41, 0x72, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x22, 0x22, 0x0a, 0x0e, 0x53, 0x75, 0x6d, 0x41, 0x72, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x03, 0x73, 0x75, 0x6d, 0x22, 0x31, 0x0a, 0x0f, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e,
	0x63, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x76, 0x61, 0x6c,
	0x75, 0x74, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x76,
	0x61, 0x6c, 0x75, 0x74, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x8c, 0x02, 0x0a, 0x10, 0x43, 0x75,
	0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x43, 0x63, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x43, 0x63, 0x79, 0x12, 0x19, 0x0a, 0x08, 0x43, 0x63, 0x79, 0x4e, 0x6d, 0x5f, 0x52, 0x55,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x63, 0x79, 0x4e, 0x6d, 0x52, 0x55, 0x12,
	0x19, 0x0a, 0x08, 0x43, 0x63, 0x79, 0x4e, 0x6d, 0x5f, 0x55, 0x5a, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x43, 0x63, 0x79, 0x4e, 0x6d, 0x55, 0x5a, 0x12, 0x1b, 0x0a, 0x09, 0x43, 0x63,
	0x79, 0x4e, 0x6d, 0x5f, 0x55, 0x5a, 0x43, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x43,
	0x63, 0x79, 0x4e, 0x6d, 0x55, 0x5a, 0x43, 0x12, 0x19, 0x0a, 0x08, 0x43, 0x63, 0x79, 0x4e, 0x6d,
	0x5f, 0x45, 0x4e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x63, 0x79, 0x4e, 0x6d,
	0x45, 0x4e, 0x12, 0x18, 0x0a, 0x07, 0x4e, 0x6f, 0x6d, 0x69, 0x6e, 0x61, 0x6c, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x4e, 0x6f, 0x6d, 0x69, 0x6e, 0x61, 0x6c, 0x12, 0x12, 0x0a, 0x04,
	0x52, 0x61, 0x74, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x52, 0x61, 0x74, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x44, 0x69, 0x66, 0x66, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x44, 0x69, 0x66, 0x66, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x65, 0x18, 0x0b, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x44, 0x61, 0x74, 0x65, 0x22, 0x22, 0x0a, 0x06, 0x50, 0x64, 0x66, 0x52,
	0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x61, 0x77, 0x50, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x61, 0x77, 0x50, 0x61, 0x74, 0x68, 0x22, 0x26, 0x0a, 0x06,
	0x50, 0x64, 0x66, 0x52, 0x65, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x61, 0x64, 0x79, 0x50,
	0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x61, 0x64, 0x79,
	0x50, 0x61, 0x74, 0x68, 0x32, 0xbd, 0x03, 0x0a, 0x10, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61,
	0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x41, 0x0a, 0x0a, 0x44, 0x69, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x12, 0x17, 0x2e, 0x64, 0x69, 0x63, 0x74, 0x2e, 0x44,
	0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x18, 0x2e, 0x64, 0x69, 0x63, 0x74, 0x2e, 0x44, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61,
	0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x53, 0x0a, 0x10,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79,
	0x12, 0x1d, 0x2e, 0x64, 0x69, 0x63, 0x74, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x69,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1e, 0x2e, 0x64, 0x69, 0x63, 0x74, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x69, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x4a, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x44, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61,
	0x72, 0x79, 0x12, 0x1a, 0x2e, 0x64, 0x69, 0x63, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x69, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b,
	0x2e, 0x64, 0x69, 0x63, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x61, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x35, 0x0a,
	0x06, 0x53, 0x75, 0x6d, 0x41, 0x72, 0x72, 0x12, 0x13, 0x2e, 0x64, 0x69, 0x63, 0x74, 0x2e, 0x53,
	0x75, 0x6d, 0x41, 0x72, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x64,
	0x69, 0x63, 0x74, 0x2e, 0x53, 0x75, 0x6d, 0x41, 0x72, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x3b, 0x0a, 0x08, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79,
	0x12, 0x15, 0x2e, 0x64, 0x69, 0x63, 0x74, 0x2e, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x64, 0x69, 0x63, 0x74, 0x2e, 0x43,
	0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x2c, 0x0a, 0x03, 0x4d, 0x61, 0x78, 0x12, 0x10, 0x2e, 0x64, 0x69, 0x63, 0x74, 0x2e,
	0x4d, 0x61, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x64, 0x69, 0x63,
	0x74, 0x2e, 0x4d, 0x61, 0x78, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x23, 0x0a, 0x03, 0x50, 0x64, 0x66, 0x12, 0x0c, 0x2e, 0x64, 0x69, 0x63, 0x74, 0x2e, 0x50, 0x64,
	0x66, 0x52, 0x65, 0x71, 0x1a, 0x0c, 0x2e, 0x64, 0x69, 0x63, 0x74, 0x2e, 0x50, 0x64, 0x66, 0x52,
	0x65, 0x73, 0x22, 0x00, 0x42, 0x0a, 0x5a, 0x08, 0x61, 0x70, 0x70, 0x2f, 0x64, 0x69, 0x63, 0x74,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dict_dict_proto_rawDescOnce sync.Once
	file_dict_dict_proto_rawDescData = file_dict_dict_proto_rawDesc
)

func file_dict_dict_proto_rawDescGZIP() []byte {
	file_dict_dict_proto_rawDescOnce.Do(func() {
		file_dict_dict_proto_rawDescData = protoimpl.X.CompressGZIP(file_dict_dict_proto_rawDescData)
	})
	return file_dict_dict_proto_rawDescData
}

var file_dict_dict_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_dict_dict_proto_goTypes = []interface{}{
	(*MaxRequest)(nil),               // 0: dict.MaxRequest
	(*MaxResponse)(nil),              // 1: dict.MaxResponse
	(*DictionaryRequest)(nil),        // 2: dict.DictionaryRequest
	(*DictionaryResponse)(nil),       // 3: dict.DictionaryResponse
	(*CreateDictionaryRequest)(nil),  // 4: dict.CreateDictionaryRequest
	(*CreateDictionaryResponse)(nil), // 5: dict.CreateDictionaryResponse
	(*GetDictionaryRequest)(nil),     // 6: dict.GetDictionaryRequest
	(*GetDictionaryResponse)(nil),    // 7: dict.GetDictionaryResponse
	(*SumArrRequest)(nil),            // 8: dict.SumArrRequest
	(*SumArrResponse)(nil),           // 9: dict.SumArrResponse
	(*CurrencyRequest)(nil),          // 10: dict.CurrencyRequest
	(*CurrencyResponse)(nil),         // 11: dict.CurrencyResponse
	(*PdfReq)(nil),                   // 12: dict.PdfReq
	(*PdfRes)(nil),                   // 13: dict.PdfRes
}
var file_dict_dict_proto_depIdxs = []int32{
	2,  // 0: dict.TranslateService.Dictionary:input_type -> dict.DictionaryRequest
	4,  // 1: dict.TranslateService.CreateDictionary:input_type -> dict.CreateDictionaryRequest
	6,  // 2: dict.TranslateService.GetDictionary:input_type -> dict.GetDictionaryRequest
	8,  // 3: dict.TranslateService.SumArr:input_type -> dict.SumArrRequest
	10, // 4: dict.TranslateService.Currency:input_type -> dict.CurrencyRequest
	0,  // 5: dict.TranslateService.Max:input_type -> dict.MaxRequest
	12, // 6: dict.TranslateService.Pdf:input_type -> dict.PdfReq
	3,  // 7: dict.TranslateService.Dictionary:output_type -> dict.DictionaryResponse
	5,  // 8: dict.TranslateService.CreateDictionary:output_type -> dict.CreateDictionaryResponse
	7,  // 9: dict.TranslateService.GetDictionary:output_type -> dict.GetDictionaryResponse
	9,  // 10: dict.TranslateService.SumArr:output_type -> dict.SumArrResponse
	11, // 11: dict.TranslateService.Currency:output_type -> dict.CurrencyResponse
	1,  // 12: dict.TranslateService.Max:output_type -> dict.MaxResponse
	13, // 13: dict.TranslateService.Pdf:output_type -> dict.PdfRes
	7,  // [7:14] is the sub-list for method output_type
	0,  // [0:7] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_dict_dict_proto_init() }
func file_dict_dict_proto_init() {
	if File_dict_dict_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dict_dict_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MaxRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dict_dict_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MaxResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dict_dict_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DictionaryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dict_dict_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DictionaryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dict_dict_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateDictionaryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dict_dict_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateDictionaryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dict_dict_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDictionaryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dict_dict_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDictionaryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dict_dict_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SumArrRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dict_dict_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SumArrResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dict_dict_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CurrencyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dict_dict_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CurrencyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dict_dict_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PdfReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dict_dict_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PdfRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dict_dict_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dict_dict_proto_goTypes,
		DependencyIndexes: file_dict_dict_proto_depIdxs,
		MessageInfos:      file_dict_dict_proto_msgTypes,
	}.Build()
	File_dict_dict_proto = out.File
	file_dict_dict_proto_rawDesc = nil
	file_dict_dict_proto_goTypes = nil
	file_dict_dict_proto_depIdxs = nil
}
